-- Autogenerated by Luapress v4.1.2
-- For available configuation options, see: luapress.org
-- Or see the default config at:
-- github.com/Fizzadar/Luapress/blob/develop/luapress/default_config.lua

local config = {
    url = 'localhost',
    template = 'torre',
}

return config
